name: cryptowallet
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.0.0
  crypto_font_icons: ^1.0.1
  cupertino_icons: ^1.0.2
  date_time_picker: ^2.1.0
  equatable: ^2.0.3
  firebase_auth: ^3.1.4
  firebase_core: ^1.8.0
  fl_chart: ^0.40.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.1
  font_awesome_flutter: ^9.2.0
  http: ^0.13.4
  step_progress_indicator: ^1.0.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Thin.ttf
          weight: 100

        - asset: fonts/Montserrat-ExtraLight.ttf
          weight: 200

        - asset: fonts/Montserrat-Light.ttf
          weight: 300

        - asset: fonts/Montserrat-Regular.ttf
          weight: 400

        - asset: fonts/Montserrat-Medium.ttf
          weight: 500

        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600

        - asset: fonts/Montserrat-Bold.ttf
          weight: 700

        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800

        - asset: fonts/Montserrat-Black.ttf
          weight: 900
